### ISSUE TITLE
Socket Timeout Bug

### ISSUE THREAD

**Issue by lsjordan** [lsjordan/switch-upgrade-tool#3]
Address an issue where the control SSH connection expires if a file copy takes a long time.

> [INFO] - [MAIN]: 10.5.21.11 - Preparing to copy file...
[SUCCESS] - [MAIN]: 10.5.21.11 - Copy success################] 100.0% - c2960s-universalk9-mz.152-2.E9.bin
[INFO] - [MAIN]: 10.5.21.12 - Preparing to copy file...
Traceback (most recent call last):
  File "C:\Tools\switch-upgrade-tool\scripts\swupgrade.py", line 253, in <module>
    main(parse_arguments())
  File "C:\Tools\switch-upgrade-tool\scripts\swupgrade.py", line 243, in main
   success = copy_file(copy_list, log)
  File "C:\Tools\switch-upgrade-tool\scripts\swupgrade.py", line 183, in copy_file
    switch.save_config()
  File "C:\Tools\switch-upgrade-tool\scripts\netdevices.py", line 209, in save_config
    self.ssh().send_command("wr mem")
  File "C:\tools\python\lib\site-packages\netmiko\base_connection.py", line 1139, in > send_command
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\tools\python\lib\site-packages\netmiko\base_connection.py", line 972, in find_prompt
    self.write_channel(self.RETURN)
  File "C:\tools\python\lib\site-packages\netmiko\base_connection.py", line 360, in write_channel
    self._write_channel(out_data)
  File "C:\tools\python\lib\site-packages\netmiko\base_connection.py", line 331, in _write_channel
    self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
  File "C:\tools\python\lib\site-packages\paramiko\channel.py", line 846, in sendall
    sent = self.send(s)
  File "C:\tools\python\lib\site-packages\paramiko\channel.py", line 801, in send
    return self._send(s, m)
  File "C:\tools\python\lib\site-packages\paramiko\channel.py", line 1180, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by lsjordan** [comment]
Resolved in commit: 
0883a3c263c9e361bedfc513798c7d6a1ed63672
